config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  get 'home/index'
  root 'home#index'

  resources :verses do
    resources :verse_commentaries
  end
  resources :chapters
  resources :book_commentaries
  resources :books, except: :destroy
  resources :sections
  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book_commentary.rb
class BookCommentary < ApplicationRecord
  belongs_to :book
  has_rich_text :comment
end

app/controllers/book_commentaries_controller.rb
class BookCommentariesController < ApplicationController
  before_action :set_book_commentary, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy]
  # GET /book_commentaries
  # GET /book_commentaries.json
  def index
    @book_commentaries = BookCommentary.all
  end

  # GET /book_commentaries/1
  # GET /book_commentaries/1.json
  def show
  end

  # GET /book_commentaries/new
  def new
    @book_commentary = BookCommentary.new
  end

  # GET /book_commentaries/1/edit
  def edit
  end

  # POST /book_commentaries
  # POST /book_commentaries.json
  def create
    @book_commentary = BookCommentary.new(book_commentary_params)

    respond_to do |format|
      if @book_commentary.save
        format.html { redirect_to @book_commentary.book, notice: 'Book commentary was successfully created.' }
        format.json { render :show, status: :created, location: @book_commentary }
      else
        format.html { render :new }
        format.json { render json: @book_commentary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /book_commentaries/1
  # PATCH/PUT /book_commentaries/1.json
  def update
    respond_to do |format|
      if @book_commentary.update(book_commentary_params)
        format.html { redirect_to @book_commentary.book, notice: 'Book commentary was successfully updated.' }
        format.json { render :show, status: :ok, location: @book_commentary }
      else
        format.html { render :edit }
        format.json { render json: @book_commentary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /book_commentaries/1
  # DELETE /book_commentaries/1.json
  def destroy
    @book_commentary.destroy
    respond_to do |format|
      format.html { redirect_to book_commentaries_url, notice: 'Book commentary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book_commentary
      @book_commentary = BookCommentary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_commentary_params
      params.require(:book_commentary).permit(:commentary, :book_id)
    end
end

app/helpers/book_commentaries_helper.rb
module BookCommentariesHelper
end

app/views/book_commentaries/edit.html.erb
<div class="row">
  <h1 class="center">Editando Comentario de <%= @book_commentary.book.name %></h1>
  <%= render 'form', book_commentary: @book_commentary %>
</div>

app/views/book_commentaries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Book Commentaries</h1>

<table>
  <thead>
    <tr>
      <th>Commentary</th>
      <th>Book</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @book_commentaries.each do |book_commentary| %>
      <tr>
        <td><%= book_commentary.commentary %></td>
        <td><%= book_commentary.book %></td>
        <td><%= link_to 'Show', book_commentary %></td>
        <td><%= link_to 'Edit', edit_book_commentary_path(book_commentary) %></td>
        <td><%= link_to 'Destroy', book_commentary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book Commentary', new_book_commentary_path %>

app/views/book_commentaries/new.html.erb
<h1>New Book Commentary</h1>

<%= render 'form', book_commentary: @book_commentary %>

<%= link_to 'Back', book_commentaries_path %>

app/views/book_commentaries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Commentary:</strong>
  <%= @book_commentary.comment %>
</p>

<p>
  <strong>Book:</strong>
  <%= @book_commentary.book %>
</p>

<%= link_to 'Edit', edit_book_commentary_path(@book_commentary) %> |
<%= link_to 'Back', book_commentaries_path %>