config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  get 'home/index'
  root 'home#index'

  resources :verses do
    resources :verse_commentaries
  end
  resources :chapters
  resources :book_commentaries
  resources :books, except: :destroy
  resources :sections
  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :section
  belongs_to :category
  has_one :book_commentary
  has_many :chapters

  has_rich_text :comment
  has_one_attached :descriptive_image do |attachable|
    attachable.variant :large, resize: "900x900"
    attachable.variant :thumb, resize: "150x150"
  end

  accepts_nested_attributes_for :book_commentary

  default_scope { order(id: :asc) }

  def next
    Book.where("id > ?", id).first
  end

  def prev
    Book.where("id < ?", id).last
  end
end

app/models/book_commentary.rb
class BookCommentary < ApplicationRecord
  belongs_to :book
  has_rich_text :comment
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  belongs_to :book
  has_many :verses

  default_scope { order(number: :asc) }

  def next
    Chapter.where('id > ? and book_id = ?', id, book_id).first
  end

  def prev
    Chapter.where('id < ? and book_id = ?', id, book_id).last
  end
end

app/models/section.rb
class Section < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/verse.rb
class Verse < ApplicationRecord
  belongs_to :chapter
  belongs_to :book
  has_one :verse_commentary

  has_rich_text :comment

  default_scope { order(number: :asc) }

  def self.random
    self.find_by('id = ?', rand(Verse.count))
  end

  def next
    Verse.where('id > ? and chapter_id = ?', id, chapter_id).first
  end

  def prev
    Verse.where('id < ? and chapter_id = ?', id, chapter_id).last
  end

  def cite
    "#{book&.name} #{chapter&.number}:#{number}"
  end
end

app/models/verse_commentary.rb
class VerseCommentary < ApplicationRecord
  belongs_to :verse
  has_rich_text :comment
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show; end

  def edit; end

  def update
    if @book.update book_params
      redirect_to @book, notice: 'Se actualizó correctamente el comentario'
    else
      render :edit, alert: 'Ocurrio un problema al guardar, intenta de nuevo.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :section_id, :category_id, :comment, :descriptive_image)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  def update
    if @category.update(category_params)
      redirect_to category_url(@category), notice: 'Se actualizo correctamente'
    else
      render :edit, notice: "Hubo un problema al actualizar"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :set_chapter, only: [:show]

  # GET /chapters
  # GET /chapters.json
  def index
    @chapters = Chapter.all
  end

  # GET /chapters/1
  # GET /chapters/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chapter
      @chapter = Chapter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chapter_params
      params.require(:chapter).permit(:number, :book_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:show]

  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.all
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      params.require(:section).permit(:name)
    end
end

app/controllers/verses_controller.rb
class VersesController < ApplicationController
  before_action :set_verse, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy]
  
  # GET /verses
  # GET /verses.json
  def index
    @verses = Verse.all
  end

  # GET /verses/1
  # GET /verses/1.json
  def show
  end

  # GET /verses/new
  def new
    @verse = Verse.new
  end

  # GET /verses/1/edit
  def edit
  end

  # POST /verses
  # POST /verses.json
  def create
    @verse = Verse.new(verse_params)

    respond_to do |format|
      if @verse.save
        format.html { redirect_to @verse, notice: 'Verse was successfully created.' }
        format.json { render :show, status: :created, location: @verse }
      else
        format.html { render :new }
        format.json { render json: @verse.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /verses/1
  # PATCH/PUT /verses/1.json
  def update
    respond_to do |format|
      if @verse.update(verse_params)
        format.html { redirect_to @verse, notice: 'Verse was successfully updated.' }
        format.json { render :show, status: :ok, location: @verse }
      else
        format.html { render :edit }
        format.json { render json: @verse.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /verses/1
  # DELETE /verses/1.json
  def destroy
    @verse.destroy
    respond_to do |format|
      format.html { redirect_to verses_url, notice: 'Verse was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_verse
      @verse = Verse.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def verse_params
      params.require(:verse).permit(:verse, :number, :chapter_id, :book_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_commentaries_helper.rb
module BookCommentariesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/verses_helper.rb
module VersesHelper
end

app/views/books/_book_header.html.slim
= image_tag url_for(book.descriptive_image), class: 'book-descriptive-image' if book.descriptive_image.attached?
.text-center.book-title
  .book-prev.text-right
    = link_to book.prev.name, book.prev if !book.prev.nil?
  h1.inline.font-bold
    = book.name
  .book-next.text-left
    = link_to book.next.name, book.next if !book.nil?

  p
    = book.section.name
    br
    = link_to book.category.name, category_path(book.category), class: :link

app/views/books/_chapters.html.slim
- active_chapter ||= nil

section
  h2.font-weight-light Capítulos
  .chapters-list.text-center
    span
    - book.chapters.each do |chapter|
      .link-container class=('active' if chapter == active_chapter)
        = link_to chapter.number, chapter_path(chapter), class: "link #{'active' if chapter == active_chapter}"

app/views/books/_form.html.slim
= form_for(@book, class: 'book-comment-edit') do |f|
  - if @book.errors.any?
    #error_explanation
      h2 
        = pluralize(@book.errors.count, "error")
        | prohibited this @book from being saved:

      ul
      - @book.errors.full_messages.each do |message|
        li = message

  .field
    = f.label :descriptive_image, 'Imágen'
    = f.file_field :descriptive_image
  = image_tag url_for(@book.descriptive_image), height: '150px' if @book.descriptive_image.attached?

  hr

  .field
    = f.label :comment, 'Comentario del Libro'
    = f.rich_text_area :comment

  .actions.text-right
    = f.submit class: 'button-send'

app/views/books/edit.html.slim
.container
  h1 Editanto el libro de #{@book.name}

  = render 'form'

app/views/books/index.html.erb
<div class="row text-center">

  <h1>Libros</h1>

  <div class="books-list-container">
    
    <div class="column medium-6">
      <h2>Antiguo Testamento</h2>
      <% @books.where('section_id = ?', 1).each do |book| %>
      <div class="books-list text-left">
        <%= link_to book.name, book_path(book), class: 'link' %>
      </div>
      <% end %>
    </div>


    <div class="column medium-6">
      <h2>Nuevo Testamento</h2>
      <% @books.where('section_id = ?', 2).each do |book| %>
      <div class="books-list text-left">
        <%= link_to book.name, book_path(book), class: 'link' %>
      </div>
      <% end %>
    </div>
  </div>

</div>

app/views/books/show.html.slim
.container
  = render partial: 'book_header', locals: { book: @book }

  = render partial: 'chapters', locals: { book: @book }

  .flex.justify-between.align-center
    h2.inline Comentario del Libro de #{@book.name}
    .text-right
      = link_to 'Editar comentario', edit_book_path(@book), class: "button primary tiny"
  == @book.comment

app/views/categories/_form.html.erb
<%= form_for(category) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, 'Nombre' %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="container">
  <h1>Editando Categoría</h1>

  <%= render 'form', category: @category %>

  <%= link_to 'Ver', @category, class: :link %> |
  <%= link_to 'Atrás', :back, class: :link %>
</div>

app/views/categories/index.html.erb
<div class="container">
  <h1>Categories</h1>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td><%= category.name %></td>
          <td><%= link_to 'Show', category %></td>
          <td><%= link_to 'Edit', edit_category_path(category) %></td>
          <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Category', new_category_path %>
</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<div class="container">
  <h1>
    Libros
    <strong><%= @category.name %></strong>
  </h1>

  <ul>
    <% @category.books.each do |book| %>
      <li>
        <%= link_to book.name, book, class: :link %>
      </li>
    <% end %>
  </ul>

  <%= link_to 'Editar', edit_category_path(@category), class: :link %> |
  <%= link_to 'Atrás', categories_path, class: :link %>
</div>

app/views/chapters/_form.html.erb
<%= form_for(chapter) do |f| %>
  <% if chapter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chapter.errors.count, "error") %> prohibited this chapter from being saved:</h2>

      <ul>
      <% chapter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %>
    <%= f.number_field :number %>
  </div>

  <div class="field">
    <%= f.label :book_id %>
    <%= f.text_field :book_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chapters/_verses.html.slim
section
  h2.font-weight-light Versos
  .verses-list.text-center
    - chapter.verses.each do |verse|
      .link-container
        = link_to verse.number, verse_path(verse), class: :link

app/views/chapters/edit.html.erb
<h1>Editing Chapter</h1>

<%= render 'form', chapter: @chapter %>

<%= link_to 'Show', @chapter %> |
<%= link_to 'Back', chapters_path %>

app/views/chapters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Chapters</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Book</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chapters.each do |chapter| %>
      <tr>
        <td><%= chapter.number %></td>
        <td><%= chapter.book %></td>
        <td><%= link_to 'Show', chapter %></td>
        <td><%= link_to 'Edit', edit_chapter_path(chapter) %></td>
        <td><%= link_to 'Destroy', chapter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chapter', new_chapter_path %>

app/views/chapters/new.html.erb
<h1>New Chapter</h1>

<%= render 'form', chapter: @chapter %>

<%= link_to 'Back', chapters_path %>

app/views/chapters/show.html.slim
.container
  = render partial: 'books/book_header', locals: { book: @chapter.book }
  .books-and-verses-container
    = render partial: 'books/chapters', locals: { book: @chapter.book, active_chapter: @chapter }
    = render partial: 'verses', locals: { chapter: @chapter }
  
  div
    h2 Versos
    div
      - @chapter.verses.each do |verse|
        .verse-link
          = link_to verse_path(verse), class: :link do
            strong
              = verse.number
              = verse.verse

app/views/sections/_form.html.erb
<%= form_for(section) do |f| %>
  <% if section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sections/edit.html.erb
<h1>Editing Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Show', @section %> |
<%= link_to 'Back', sections_path %>

app/views/sections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sections</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sections.each do |section| %>
      <tr>
        <td><%= section.name %></td>
        <td><%= link_to 'Show', section %></td>
        <td><%= link_to 'Edit', edit_section_path(section) %></td>
        <td><%= link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Section', new_section_path %>

app/views/sections/new.html.erb
<h1>New Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Back', sections_path %>

app/views/sections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @section.name %>
</p>

<%= link_to 'Edit', edit_section_path(@section) %> |
<%= link_to 'Back', sections_path %>