config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  get 'home/index'
  root 'home#index'

  resources :verses do
    resources :verse_commentaries
  end
  resources :chapters
  resources :book_commentaries
  resources :books, except: :destroy
  resources :sections
  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/verse_commentary.rb
class VerseCommentary < ApplicationRecord
  belongs_to :verse
  has_rich_text :comment
end

app/controllers/verse_commentaries_controller.rb
class VerseCommentariesController < ApplicationController
  before_action :set_verse_commentary, only: [:show, :edit, :update, :destroy]
  before_action :set_verse, only: [:new, :create, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  # GET /verse_commentaries
  # GET /verse_commentaries.json
  def index
    @verse_commentaries = VerseCommentary.all
  end

  # GET /verse_commentaries/1
  # GET /verse_commentaries/1.json
  def show
  end

  # GET /verse_commentaries/new
  def new
    @verse_commentary = @verse.build_verse_commentary
  end

  # GET /verse_commentaries/1/edit
  def edit
  end

  # POST /verse_commentaries
  # POST /verse_commentaries.json
  def create
    @verse_commentary = @verse.build_verse_commentary(verse_commentary_params)

    respond_to do |format|
      if @verse_commentary.save
        format.html { redirect_to @verse, notice: 'Verse commentary was successfully created.' }
        format.json { render :show, status: :created, location: @verse_commentary }
      else
        format.html { render :new }
        format.json { render json: @verse_commentary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /verse_commentaries/1
  # PATCH/PUT /verse_commentaries/1.json
  def update
    respond_to do |format|
      if @verse_commentary.update(verse_commentary_params)
        format.html { redirect_to @verse, notice: 'Verse commentary was successfully updated.' }
        format.json { render :show, status: :ok, location: @verse_commentary }
      else
        format.html { render :edit }
        format.json { render json: @verse_commentary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /verse_commentaries/1
  # DELETE /verse_commentaries/1.json
  def destroy
    @verse_commentary.destroy
    respond_to do |format|
      format.html { redirect_to verse_commentaries_url, notice: 'Verse commentary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_verse_commentary
      @verse_commentary = VerseCommentary.find(params[:id])
    end

    def set_verse
      @verse =  Verse.find(params[:verse_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def verse_commentary_params
      params.require(:verse_commentary).permit(:commentary, :verse_id)
    end
end

app/helpers/verse_commentaries_helper.rb
module VerseCommentariesHelper
end

app/views/verse_commentaries/_form.html.erb
<%= form_for([@verse, @verse_commentary]) do |f| %>
  <% if verse_commentary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(verse_commentary.errors.count, "error") %> prohibited this verse_commentary from being saved:</h2>

      <ul>
      <% verse_commentary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.rich_text_area :comment %>
  </div>

  <div class="actions text-right">
    <%= f.submit class: "button" %>
  </div>
<% end %>

app/views/verse_commentaries/edit.html.erb
<div class="row">
  <h1>Editando Comentario <small><%= @verse.book.name %> <%= @verse.chapter.number %>:<%= @verse.number %></small></h1>
  <%= render 'form', verse_commentary: @verse_commentary %>
</div>

app/views/verse_commentaries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Verse Commentaries</h1>

<table>
  <thead>
    <tr>
      <th>Commentary</th>
      <th>Verse</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @verse_commentaries.each do |verse_commentary| %>
      <tr>
        <td><%= verse_commentary.commentary %></td>
        <td><%= verse_commentary.verse %></td>
        <td><%= link_to 'Show', verse_commentary %></td>
        <td><%= link_to 'Edit', edit_verse_commentary_path(verse_commentary) %></td>
        <td><%= link_to 'Destroy', verse_commentary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Verse Commentary', new_verse_commentary_path %>

app/views/verse_commentaries/new.html.erb
<h1>New Verse Commentary</h1>

<%= render 'form', verse_commentary: @verse_commentary %>